### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by joekru** [mivano/azure-cost-cli#168]
Starting on July 12, 2024, a daily script I have running the commands:

azure-cost budgets -o json -s $subscriptionID --query "[?Name=='Monthly Budget']"

azure-cost accumulatedCost -s "$($subscriptionId)" -g "$($resourceGroupName)" -o json

Stopped returning info.  

I am getting error like:

`System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AzureCostCli.CostApi.AzureCostApiRetriever.ExecutePagedCallToCostApi(Boolean includeDebugOutput, Object payload, Uri uri) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/CostApi/AzureCostApiRetriever.cs:line 167
   at AzureCostCli.CostApi.AzureCostApiRetriever.RetrieveCosts(Boolean includeDebugOutput, Scope scope, String[] filter, MetricType metric, TimeframeType timeFrame, DateOnly from, DateOnly to) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/CostApi/AzureCostApiRetriever.cs:line 284
   at AzureCostCli.Commands.AccumulatedCost.AccumulatedCostCommand.<>c__DisplayClass4_0.<<ExecuteAsync>b__0>d.MoveNext() in /home/runner/work/azure-cost-cli/azure-cost-cli/src/Commands/AccumulatedCost/AccumulatedCostCommand.cs:line 110
--- End of stack trace from previous location ---
   at AzureCostCli.OutputFormatters.SpectreConsole.StatusExt.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /home/runner/work/azure-cost-cli/azure-cost-cli/src/OutputFormatters/SpectreConsole/StatusExt.cs:line 99
--- End of stack trace from previous location ---
   at AzureCostCli.OutputFormatters.SpectreConsole.StatusExt.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func)
   at Spectre.Console.Progress.StartAsync[T](Func`2 action)
   at AzureCostCli.OutputFormatters.SpectreConsole.StatusExt.StartAsync[T](String status, Func`2 func)
   at AzureCostCli.OutputFormatters.SpectreConsole.StatusExt.StartAsync(String status, Func`2 action) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/OutputFormatters/SpectreConsole/StatusExt.cs:line 97
   at AzureCostCli.Commands.AccumulatedCost.AccumulatedCostCommand.ExecuteAsync(CommandContext context, AccumulatedCostSettings settings) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/Commands/AccumulatedCost/AccumulatedCostCommand.cs:line 91
   at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in /_/src/Spectre.Console.Cli/Internal/CommandExecutor.cs:line 166`

Did something happen with the API being called by azure-cost?  The script ran unchanged on previous days of July up through July 11.

**Comment by joekru** [comment]
Tool 'azure-cost-cli' was reinstalled with the stable version (version '0.41.0').

**Comment by mivano** [comment]
Hmm, I m not aware of any changes, but can you give it a try with the `-debug` option? That should show the actual message for the 400.

**Comment by joekru** [comment]
Looks like someone in my org changed IAM permissions on me unexpectedly.

**Comment by mivano** [comment]
Thanks for getting back to this. That makes sense.
