### ISSUE TITLE
CSV Output support for 'azure-cost budgets -s xxx-xxx-xxx -o csv'

### ISSUE THREAD

**Issue by satyaki1008** [mivano/azure-cost-cli#176]
I am using the azure-cost cli tool in my powershell script. I have successfully ran almost all commands and extracted data except for azure-cost budgets. I want the data output format in csv and looks like the csv option for azure-cost budgets is throwing some error.

`PS C:\Users\SATYGUHA> $a = azure-cost budgets --subscription xxx-xxx-xxx-xxx -o csv
CsvHelper.WriterException: An unexpected error occurred. See inner exception for details.
IWriter state:
   Row: 2
   Index: 8
   HeaderRecord:
2

 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AzureCostCli.OutputFormatters.CustomDoubleConverter.ConvertToString(Object value, IWriterRow row, MemberMapData memberMapData) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/OutputFormatters/CsvOutputFormatter.cs:line 185
   at CsvHelper.TypeConversion.NullableConverter.ConvertToString(Object value, IWriterRow row, MemberMapData memberMapData)
   at lambda_method17(Closure, Object)
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   --- End of inner exception stack trace ---
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   at AzureCostCli.OutputFormatters.CsvOutputFormatter.ExportToCsv(Boolean skipHeader, IEnumerable`1 resources) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/OutputFormatters/CsvOutputFormatter.cs:line 157
   at AzureCostCli.OutputFormatters.CsvOutputFormatter.WriteBudgets(BudgetsSettings settings, IEnumerable`1 budgets) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/OutputFormatters/CsvOutputFormatter.cs:line 32
   at AzureCostCli.Commands.Budgets.BudgetsCommand.ExecuteAsync(CommandContext context, BudgetsSettings settings) in /home/runner/work/azure-cost-cli/azure-cost-cli/src/Commands/Budgets/BudgetsCommand.cs:line 68
   at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in /_/src/Spectre.Console.Cli/Internal/CommandExecutor.cs:line 166`

This is the error I am getting. Kindly evaluate this and let me know if there are any questions. Also other output formats for the budget command are working fine.

**Comment by mivano** [comment]
Found the issue. Will be fixed in the 0.43 release. Thanks for the report.
